proc format;
value $CenDiv
'CT' = '1' 
'ME' = '1' 
'MA' = '1' 
'NH' = '1' 
'RI' = '1' 
'VT' = '1'
 
'NJ' = '2' 
'NY' = '2' 
'PA' = '2' 

'DE' = '3' 
'DC' = '3' 
'FL' = '3' 
'GA' = '3' 
'MD' = '3' 
'SC' = '3' 
'VA' = '3' 
'WV' = '3' 
'NC' = '3' 
'PR' = '3'

'IL' = '4' 
'IN' = '4' 
'MI' = '4' 
'OH' = '4' 
'WI' = '4'

'AL' = '5' 
'KY' = '5' 
'MS' = '5' 
'TN' = '5'

'IA' = '6' 
'KS' = '6' 
'MN' = '6' 
'MO' = '6' 
'NE' = '6' 
'ND' = '6' 
'SD' = '6'

'AR' = '7' 
'LA' = '7' 
'OK' = '7' 
'TX' = '7'

'AZ' = '8' 
'CO' = '8' 
'ID' = '8' 
'MT' = '8' 
'NV' = '8' 
'NM' = '8' 
'UT' = '8' 
'WY' = '8'

'CA' = '9' 
'OR' = '9' 
'WA' = '9' 
'AK' = '9' 
'HI' = '9'

OTHER = '0'
;

value $CnDvNm
'CT'='New England'
'ME'='New England'
'MA'='New England'
'NH'='New England'
'RI'='New England'
'VT'='New England'
'NJ'='Middle Atlantic'
'NY'='Middle Atlantic'
'PA'='Middle Atlantic'
'DE'='South Atlantic'
'DC'='South Atlantic'
'FL'='South Atlantic'
'GA'='South Atlantic'
'MD'='South Atlantic'
'SC'='South Atlantic'
'VA'='South Atlantic'
'WV'='South Atlantic'
'NC'='South Atlantic'
'PR'='South Atlantic'
'IL'='East North Central'
'IN'='East North Central'
'MI'='East North Central'
'OH'='East North Central'
'WI'='East North Central'
'AL'='East South Central'
'KY'='East South Central'
'MS'='East South Central'
'TN'='East South Central'
'IA'='West North Central'
'KS'='West North Central'
'MN'='West North Central'
'MO'='West North Central'
'NE'='West North Central'
'ND'='West North Central'
'SD'='West North Central'
'AR'='West South Central'
'LA'='West South Central'
'OK'='West South Central'
'TX'='West South Central'
'AZ'='Mountain'
'CO'='Mountain'
'ID'='Mountain'
'MT'='Mountain'
'NV'='Mountain'
'NM'='Mountain'
'UT'='Mountain'
'WY'='Mountain'
'CA'='Pacific'
'OR'='Pacific'
'WA'='Pacific'
'AK'='Pacific'
'HI'='Pacific'

Other='ERROR'
;
run;
