dt <- data(iris)
iris.rf <- randomForest(iris[,-5],iris[,5],prox=TRUE)
print(iris.rf)
is.data.frame(dt)
row(iris)
iris.rf <- randomForest(x=iris[,-5],y=iris[,5],proximity=TRUE,importance=TRUE,localImp=TRUE)
round(importance(iris.rf),2)
iris.rf$proximity[1:5,1:5]
iris.mds <- cmdscale(1-iris.rf$proximity,eig=TRUE)
print(iris.mds)
op <- par(pty="s")
pairs(cbind(iris[,1:4],iris.mds$points),cex=0.6,gap=0,col=c("red","green","blue")[as.numeric(iris$Species)],main="Iris Data: Predictiors and MDS of Promixity Based on RandomForest")
set.seed(17)
iris.urf <- randomForest(iris[,-5])
MDSplot(iris.urf,iris$Species)
iris.rf2 <- randomForest(iris[1:4],iris$Species,sampsize=c(20,50,50),maxnode=4,ntree=30)
print(iris.rf2)